name: example
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  deriv_auth:
    path: ../
  flutter_bloc: ^8.1.3
  http: ^0.13.6
  device_preview: ^1.1.0
  deriv_http_client:
    git:
      url: git@github.com:regentmarkets/flutter-deriv-packages.git
      path: packages/deriv_http_client
      ref: deriv_http_client-v1.0.0
  deriv_passkeys:
    git:
      url: git@github.com:regentmarkets/flutter-deriv-packages.git
      path: packages/deriv_passkeys
      ref: c9b906bc20edbc94d0ca99f2211b142efa3aaf2e

dependency_overrides:
  flutter_deriv_api:
    git:
      url: git@github.com:deriv-com/flutter-deriv-api.git
      ref: 64ad3673598ad807b43f751fc2ec7bc5ef01203e
  deriv_ui:
    git:
      url: git@github.com:regentmarkets/flutter-deriv-packages.git
      path: packages/deriv_ui
      ref: deriv_ui-v0.0.6+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
