name: update_checker
description: Check and retrieve update information from the server for the given package.
version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_database: ^4.0.0
  package_info: ^0.4.3
  flutter_bloc: ^6.0.1
  equatable: ^1.2.5
  bloc: ^6.1.0
  rxdart: ^0.24.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: any
  test: any
