name: update_checker
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_database: ^3.1.6
  package_info: ^0.4.0+13
  flutter_bloc: ^3.2.0
  equatable: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: any
  test: any
  mockito: any
